# Site settings
title: A portfolio of writing from my freshman year.
description: A portfolio of writing from my freshman year.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cameron Kennedy
user_description: Someone who uses writing for utility, and little else.
user_title: Software Developer
email: cvkennedy@omniproject.net
twitter_username: 
github_username:  m3rc1fulcameron
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
